name: '1515'
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.2=pyhc872135_1
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asttokens==3.0.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.0
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.121.2
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - grpcio==1.76.0
      - h11==0.16.0
      - humanfriendly==10.0
      - idna==3.11
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - onnxruntime==1.23.2
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - prompt-toolkit==3.0.52
      - protobuf==4.21.2
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.49.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - thop==0.1.1-2209072238
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - yacs==0.1.8
prefix: /opt/anaconda3/envs/1515
